/**
 * Machine-generated file. Do not modify.
 */

#ifndef _SPECIALCLASSES_H
#define _SPECIALCLASSES_H
#define JAVA_LANG_OBJECT 0
#define JAVA_LANG_THREAD 1
#define JAVA_LANG_STRING 2
#define JAVA_LANG_THROWABLE 3
#define JAVA_LANG_ERROR 4
#define JAVA_LANG_OUTOFMEMORYERROR 5
#define JAVA_LANG_NOSUCHMETHODERROR 6
#define JAVA_LANG_STACKOVERFLOWERROR 7
#define JAVA_LANG_NULLPOINTEREXCEPTION 8
#define JAVA_LANG_CLASSCASTEXCEPTION 9
#define JAVA_LANG_ARITHMETICEXCEPTION 10
#define JAVA_LANG_ARRAYINDEXOUTOFBOUNDSEXCEPTION 11
#define JAVA_LANG_ILLEGALARGUMENTEXCEPTION 12
#define JAVA_LANG_INTERRUPTEDEXCEPTION 13
#define JAVA_LANG_ILLEGALSTATEEXCEPTION 14
#define JAVA_LANG_ILLEGALMONITORSTATEEXCEPTION 15
#define JAVA_LANG_THREADDEATH 16
#endif // _SPECIALCLASSES_H
